# Generated by Django 4.2.16 on 2025-07-19 04:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("budget_min", models.DecimalField(decimal_places=2, max_digits=15)),
                ("budget_max", models.DecimalField(decimal_places=2, max_digits=15)),
                ("preferred_locations", models.JSONField(blank=True, default=list)),
                ("property_type", models.CharField(default="apartment", max_length=20)),
                ("desired_area_min", models.PositiveIntegerField(default=50)),
                ("desired_area_max", models.PositiveIntegerField(default=200)),
                ("rooms_min", models.PositiveIntegerField(default=1)),
                ("rooms_max", models.PositiveIntegerField(default=4)),
                ("prefers_parking", models.BooleanField(default=True)),
                ("prefers_garden", models.BooleanField(default=False)),
                ("prefers_balcony", models.BooleanField(default=True)),
                ("prefers_elevator", models.BooleanField(default=False)),
                ("prefers_furnished", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("converted", "Converted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("embedding", models.BinaryField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "apps_contacts_contact",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="apps_contac_status_949317_idx"
                    ),
                    models.Index(
                        fields=["property_type"], name="apps_contac_propert_e3921f_idx"
                    ),
                    models.Index(
                        fields=["budget_min", "budget_max"],
                        name="apps_contac_budget__64ad24_idx",
                    ),
                ],
            },
        ),
    ]
