# Generated by Django 4.2.16 on 2025-07-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("address", models.TextField()),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "area",
                    models.PositiveIntegerField(help_text="Area in square meters"),
                ),
                ("rooms", models.PositiveIntegerField(default=0)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("house", "House"),
                            ("villa", "Villa"),
                            ("studio", "Studio"),
                            ("office", "Office"),
                            ("land", "Land"),
                            ("commercial", "Commercial"),
                        ],
                        default="apartment",
                        max_length=20,
                    ),
                ),
                ("has_parking", models.BooleanField(default=False)),
                ("has_garden", models.BooleanField(default=False)),
                ("has_balcony", models.BooleanField(default=False)),
                ("has_elevator", models.BooleanField(default=False)),
                ("is_furnished", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("sold", "Sold"),
                            ("rented", "Rented"),
                            ("pending", "Pending"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("embedding", models.BinaryField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "apps_properties_property",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["city", "property_type"],
                        name="apps_proper_city_cca42f_idx",
                    ),
                    models.Index(fields=["price"], name="apps_proper_price_d4624d_idx"),
                    models.Index(
                        fields=["status"], name="apps_proper_status_e5de69_idx"
                    ),
                ],
            },
        ),
    ]
